# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kakao_user',
            name='hufs_pwd',
        ),
    ]
