# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_kakao_user_hufs_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakao_user',
            name='hufs_pwd',
            field=models.CharField(default='empty', max_length=50),
            preserve_default=False,
        ),
    ]
